### STAGE 1:BUILD ###
FROM node:14-alpine AS build
WORKDIR /home/node
COPY angular-app/package.json /home/node
RUN npm cache clean --force
RUN npm install
COPY angular-app /home/node
RUN ls /home/node
# USER root
RUN npm install -g @angular/cli
RUN npm run build --prod
RUN ls /home/node/dist

### STAGE 2:RUN ###
FROM nginx:latest AS ngi
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /home/node/dist/Angular11JwtAuth /usr/share/nginx/html/
EXPOSE 80
RUN ls /usr/share/nginx/html