#
# Build stage
#
FROM maven:3.8-eclipse-temurin-11-alpine AS build
COPY spring-data-mongo/src /home/app/src
COPY spring-data-mongo/pom.xml /home/app/
WORKDIR /home/app
RUN mvn clean install
RUN mvn clean package
RUN ls /home/app/target
#
# Package stage
#
FROM openjdk:11-jre-slim
COPY --from=build /home/app/target/spring-data-mongo-0.0.1-SNAPSHOT.jar /usr/local/lib/demo.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/demo.jar"]